CoreGenericRepo/Models/DTO/MovieVM.cs
using CoreGenericRepo.Models.Entity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections;
using System.Collections.Generic;

namespace CoreGenericRepo.Models.DTO
{
    public class MovieVM
    {
        public ICollection<MovieType> mtList { get; set; }
        public MovieType MovieTypes { get; set; }
        public ICollection<Movie> mList { get; set; }
        public Movie Movies { get; set; }

    }
}

CoreGenericRepo/Models/DataContext.cs
using CoreGenericRepo.Models.Entity;
using Microsoft.EntityFrameworkCore;

namespace CoreGenericRepo.Models
{
    public class DataContext:DbContext
    {
        public DataContext(DbContextOptions<DataContext>options):base(options)
        {

        }
        public DbSet<Movie> Movies { get; set; }
        public DbSet<MovieType> MovieTypes { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<MovieType>().HasMany(x => x.Movies).WithOne(x => x.MovieType).HasForeignKey(x => x.MovieTypeID);
        }

    }
}

CoreGenericRepo/Models/Entity/Movie.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreGenericRepo.Models.Entity
{
    public class Movie
    {
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string MovieDescription { get; set; }
        public string MovieImage { get; set; }
        public int MovieTypeID { get; set; }
        public MovieType MovieType { get; set; }
    }
}

CoreGenericRepo/Models/Entity/MovieType.cs
using System.Collections;
using System.Collections.Generic;

namespace CoreGenericRepo.Models.Entity
{
    public class MovieType
    {
        public int MovieTypeID { get; set; }
        public string MovieTypeName { get; set; }
        public ICollection<Movie> Movies { get; set; }
    }
}

CoreGenericRepo/Models/ErrorViewModel.cs
using System;

namespace CoreGenericRepo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreGenericRepo/Controllers/HomeController.cs
using CoreGenericRepo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CoreGenericRepo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CoreGenericRepo/Controllers/MovieController.cs
using CoreGenericRepo.Models.DTO;
using CoreGenericRepo.Models.Entity;
using CoreGenericRepo.Repository;
using Microsoft.AspNetCore.Mvc;

namespace CoreGenericRepo.Controllers
{
    public class MovieController : Controller
    {
        private IBaseRepository<Movie> repo;
        private IBaseRepository<MovieType> mtRepo;
        private 
        MovieVM mvm = new MovieVM();
        public MovieController(IBaseRepository<Movie> _repo, IBaseRepository<MovieType> _mtrepo)
        {
            repo = _repo;
            mtRepo = _mtrepo;
        }
        public IActionResult Index()
        {
            mvm.mList = repo.List();
            mvm.mtList = mtRepo.List();

           return View(mvm);
        }
        public IActionResult Insert()
        {
            mvm.mtList = mtRepo.List();
            return View(mvm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(MovieVM model)
        {
            if (model.Movies != null)
            {
                if (model.Movies.MovieImage == null)
                {
                    model.Movies.MovieImage = "default.jpg";
                }
                repo.Add(model.Movies);
                repo.Save();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            if (id != 0)
            {
                mvm.Movies = repo.Find(id);
                mvm.mtList = mtRepo.List();
            }
            return View(mvm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, MovieVM model)
        {
            if (ModelState.IsValid)
            {
                Movie selectedm = repo.Find(id);

                if(model.Movies.MovieImage == null)
                {
                    selectedm.MovieImage = "default.jpg";
                }
                else
                {
                    selectedm.MovieImage = model.Movies.MovieImage;
                }
                selectedm.MovieName = model.Movies.MovieName;
                selectedm.MovieDescription = model.Movies.MovieDescription;              
                selectedm.MovieTypeID = model.Movies.MovieTypeID;
                repo.Save();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
        public IActionResult Delete(int id)
        {
            if (id != 0)
            {
                mvm.Movies = repo.Find(id);
                repo.Delete(mvm.Movies);
                repo.Save();
            }
            return RedirectToAction("Index");
        }
        public IActionResult Detail(int id)
        {
            mvm.Movies = repo.Find(id);
            mvm.mtList = mtRepo.List();

            return View(mvm);
        }
    }
}

CoreGenericRepo/Controllers/MovieTypeController.cs
using CoreGenericRepo.Models.DTO;
using CoreGenericRepo.Models.Entity;
using CoreGenericRepo.Repository;
using Microsoft.AspNetCore.Mvc;

namespace CoreGenericRepo.Controllers
{
    public class MovieTypeController : Controller
    {
        private IBaseRepository<MovieType> repo;
        MovieVM mtvm = new MovieVM();
        public MovieTypeController(IBaseRepository<MovieType> _repo)
        {
            repo = _repo;
        }
        public IActionResult Index()
        {
            return View(repo.List());
        }
        public IActionResult Insert()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert(MovieVM model)
        {
                if(model.MovieTypes != null)
                {
                    repo.Add(model.MovieTypes);
                    repo.Save();
                }
            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            if(id != 0)
            { 
            mtvm.MovieTypes = repo.Find(id);
            }
            return View(mtvm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, MovieVM model)
        {
            if (ModelState.IsValid)
            {
                MovieType selectedmt = repo.Find(id);
                if(model.MovieTypes.MovieTypeName != null || model.MovieTypes.MovieTypeName != string.Empty)
                {
                    selectedmt.MovieTypeName = model.MovieTypes.MovieTypeName;
                }
                repo.Save();
                return RedirectToAction("Index");
            }
            return NotFound();
        }
        public IActionResult Detail(int id)
        {
            mtvm.MovieTypes = repo.Find(id);

            return View(mtvm);
        }
        public IActionResult Delete(int id)
        {
            if(id != 0)
            { 
            mtvm.MovieTypes = repo.Find(id);
            repo.Delete(mtvm.MovieTypes);
            repo.Save();
            }
            return RedirectToAction("Index");
        }
    }
}

CoreGenericRepo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreGenericRepo/Views/Movie/Detail.cshtml
@model CoreGenericRepo.Models.DTO.MovieVM

@{
    var title = "Film Detayı";
}




<form method="post">
    <div class="row border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Movies.MovieID" />
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 pt-4">
             <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieImage" class="form-control"></label>
                </div>
                <div class="col-8">
                    <img src="~/img/@Model.Movies.MovieImage" />

                </div>
            </div>
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieID" class="form-control"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieID" class="form-control" readonly />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieName" class="form-control"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieName" class="form-control" readonly/>
                    <span asp-validation-for="Movies.MovieName" class="text-danger"></span>
                </div>
            </div>
             <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieDescription" class="form-control"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieDescription" class="form-control" readonly/>
                    <span asp-validation-for="Movies.MovieDescription" class="text-danger"></span>
                </div>
            </div>
             <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieType.MovieTypeName" class="form-control"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieType.MovieTypeName" class="form-control" readonly/>
                    <span asp-validation-for="Movies.MovieType.MovieTypeName" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <a asp-action="Index" class="btn btn-success form-control">Listeye Geri Dön</a>

                </div>
            </div>
        </div>
    </div>
</form>

CoreGenericRepo/Views/Movie/Index.cshtml
@model CoreGenericRepo.Models.DTO.MovieVM
<br />
<br />
<div class="border p-4 bg-white">
    <div class="row">
        <div class="col-10">
            <h2 class="text-info">Film Listesi</h2>
        </div>
        <div class="col-2">
            <a class="btn btn-info form-control" asp-action="Insert">Film Ekle</a>
        </div>
    </div>
    <div>
        @if (Model.mList.Count() > 0)
        {
            <table class="table table-striped border">
                <tbody>
                    <tr class="table-secondary">
                        <th>ID</th>
                        <th>Adı</th>
                        <th>Açıklama</th>
                        <th>Türü</th>
                        <th colspan="3">İşlemler</th>


                        <th></th>
                    </tr>
                    @foreach (var item in Model.mList)
                    {
                <tr>
                    <td>@item.MovieID</td>
                    <td>@item.MovieName</td>
                    <td>@item.MovieDescription</td>
                    <td>@item.MovieType.MovieTypeName</td>
                    <td></td>

                    <td>
                        <a class="btn btn-primary text-white" asp-action="Update" asp-route-id="@item.MovieID">Update</a>
                        <a class="btn btn-danger text-white" asp-action="Detail" asp-route-id="@item.MovieID">Detail</a>
                        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.MovieID">Delete</a>


                    </td>
                </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Kayıt Bulunamadı!</p>
        }

    </div>
</div>

CoreGenericRepo/Views/Movie/Insert.cshtml
@model CoreGenericRepo.Models.DTO.MovieVM


@{
    var title = "Film Oluştur";
}

<div>
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Movies.MovieID" />
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 p-4">

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieName" class="form-control" />
                    <span asp-validation-for="Movies.MovieName" class="text-danger"></span>
                </div>
            </div>
             <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieDescription"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieDescription" class="form-control" />
                    <span asp-validation-for="Movies.MovieDescription" class="text-danger"></span>
                </div>
            </div>
              <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieImage"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieImage" class="form-control" />
                    <p>Example: moviename.jpg</p>
                    <span asp-validation-for="Movies.MovieImage" class="text-danger"></span>
                </div>
            </div>
             <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieTypeID"></label>
                </div>
                <div class="col-8">
                    <select class="form-control" id="exampleFormControlSelect1" asp-for="Movies.MovieTypeID" asp-items="@(new SelectList(Model.mtList,"MovieTypeID","MovieTypeName"))">
        <option value="0">--- Tür Seçiniz ---</option>
    </select>
                    <span asp-validation-for="Movies.MovieImage" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <button type="submit" class="btn btn-primary form-control">Oluştur</button>
                </div>
                <div class="col-6">
                    <a asp-action="Index" class="btn btn-success form-control">Listeye Geri Dön</a>
                </div>
            </div>
        </div>
    </form>
</div>

CoreGenericRepo/Views/Movie/Update.cshtml
@model CoreGenericRepo.Models.DTO.MovieVM


@{
    var title = "Film Güncelle";
}

<div>
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Movies.MovieID" />
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 p-4">

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieName" class="form-control" />
                    <span asp-validation-for="Movies.MovieName" class="text-danger"></span>
                </div>
            </div>
             <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieDescription"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieDescription" class="form-control" />
                    <span asp-validation-for="Movies.MovieDescription" class="text-danger"></span>
                </div>
            </div>
              <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieImage"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Movies.MovieImage" class="form-control" />
                    <p>Example: moviename.jpg</p>
                    <span asp-validation-for="Movies.MovieImage" class="text-danger"></span>
                </div>
            </div>
             <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Movies.MovieTypeID"></label>
                </div>
                <div class="col-8">
                    <select class="form-control" id="exampleFormControlSelect1" asp-for="Movies.MovieTypeID" asp-items="@(new SelectList(Model.mtList,"MovieTypeID","MovieTypeName"))">
        <option value="0">--- Tür Seçiniz ---</option>
    </select>
                    <span asp-validation-for="Movies.MovieImage" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-3">
                    <button type="submit" class="btn btn-primary form-control">Güncelle</button>
                </div>
                <div class="col-4">
                    <a asp-action="Index" class="btn btn-success form-control">Listeye Geri Dön</a>
                </div>
            </div>
        </div>
    </form>
</div>

CoreGenericRepo/Views/MovieType/Detail.cshtml
@model CoreGenericRepo.Models.DTO.MovieVM

@{
    var title = "Tür Detayı";
}




<form method="post">
    <div class="row border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="MovieTypes.MovieTypeID" />
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 pt-4">
            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MovieTypes.MovieTypeID" class="form-control"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MovieTypes.MovieTypeID" class="form-control" readonly />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MovieTypes.MovieTypeName" class="form-control"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MovieTypes.MovieTypeName" class="form-control" readonly/>
                    <span asp-validation-for="MovieTypes.MovieTypeName" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <a asp-action="Index" class="btn btn-success form-control">Listeye Geri Dön</a>

                </div>
            </div>
        </div>
    </div>
</form>

CoreGenericRepo/Views/MovieType/Index.cshtml
@model IEnumerable<CoreGenericRepo.Models.Entity.MovieType>

<br />
<br />
<div class="border p-4 bg-white">
    <div class="row">
        <div class="col-10">
            <h2 class="text-info">Tür Listesi</h2>
        </div>
        <div class="col-2">
            <a class="btn btn-info form-control" asp-action="Insert">Tür Ekle</a>
        </div>
    </div>
    <div>
        @if (Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tbody>
                    <tr class="table-secondary">
                        <th>Tür ID</th>
                        <th>Tür Adı</th>
                        <th colspan="3">İşlemler</th>


                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                <tr>
                    <td>@item.MovieTypeID</td>
                    <td>@item.MovieTypeName</td>

                    <td>
                        <a class="btn btn-primary text-white" asp-action="Update" asp-route-id="@item.MovieTypeID">Update</a>
                        <a class="btn btn-danger text-white" asp-action="Detail" asp-route-id="@item.MovieTypeID">Detail</a>
                        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.MovieTypeID">Delete</a>


                    </td>
                </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Kayıt Bulunamadı!</p>
        }

    </div>
</div>

CoreGenericRepo/Views/MovieType/Insert.cshtml
@model CoreGenericRepo.Models.DTO.MovieVM


@{
    var title = "Tür Oluştur";
}

<div>
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="MovieTypes.MovieTypeID" />
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 p-4">

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MovieTypes.MovieTypeName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MovieTypes.MovieTypeName" class="form-control" />
                    <span asp-validation-for="MovieTypes.MovieTypeName" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <button type="submit" class="btn btn-primary form-control">Oluştur</button>
                </div>
                <div class="col-6">
                    <a asp-action="Index" class="btn btn-success form-control">Listeye Geri Dön</a>
                </div>
            </div>
        </div>
    </form>
</div>

CoreGenericRepo/Views/MovieType/Update.cshtml
@model CoreGenericRepo.Models.DTO.MovieVM


@{
    var title = "Tür Güncelle";
}

<div>
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="MovieTypes.MovieTypeID" />
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 p-4">

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="MovieTypes.MovieTypeName"></label>
                </div>
                <div class="col-8">
                    <input asp-for="MovieTypes.MovieTypeName" class="form-control" />
                    <span asp-validation-for="MovieTypes.MovieTypeName" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <button type="submit" class="btn btn-primary form-control">Güncelle</button>
                </div>
                <div class="col-6">
                    <a asp-action="Index" class="btn btn-success form-control">Listeye Geri Dön</a>
                </div>
            </div>
        </div>
    </form>
</div>

CoreGenericRepo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreGenericRepo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreGenericRepo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MovieType" asp-action="Index">Film Türleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Filmler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CoreGenericRepo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>